services:
  openobserve:
    image: public.ecr.aws/zinclabs/openobserve:latest
    restart: unless-stopped
    ports:
      - "5080:5080"
    environment:
      ZO_ROOT_USER_EMAIL: admin@test.de
      ZO_ROOT_USER_PASSWORD: password1234
    volumes:
      - openobserve_data:/data

volumes:
  openobserve_data:
