spring:
  application:
    name: OpenFireStationManager
  datasource:
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
    url: ${DB_URL:jdbc:postgresql://localhost:5432/ofsm}

server:
  forward-headers-strategy: framework

app:
  auth:
    cookie-name: OFSM_AUTH
    jwt-signing-secret: ${JWT_SIGNING_SECRET:SOME_32_CHARACTERS_LONG_KEY_HERE}

springdoc:
  swagger-ui:
    enabled: true
  api-docs:
    enabled: true
    path: /schema.json
