spring:
  application:
    name: OpenFireStationManager
  docker:
    compose:
      file: ./compose.yml
      lifecycle-management: start_only

app:
  auth:
    cookie-name: OFSM_AUTH
    jwt-signing-secret: ${JWT_SIGNING_SECRET:SOME_32_CHARACTERS_LONG_KEY_HERE}

springdoc:
  swagger-ui:
    enabled: true
    path: /api/public/swagger-ui.html
  api-docs:
    enabled: true
    path: /api/public/schema.json
