/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/api/admin/users/{id}/password": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put: operations["changePassword"]
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/api/public/setup/initial-admin": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    post: operations["initializeAdmin"]
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/api/public/auth/logout": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    post: operations["logout"]
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/api/public/auth/login": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    post: operations["login"]
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/api/clothing/types": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** List all protective clothing types */
    get: operations["getAllTypes"]
    put?: never
    /** Create a new protective clothing type */
    post: operations["createType"]
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/api/clothing/relocation": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /** Relocate clothing items to a target location */
    post: operations["relocate"]
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/api/clothing/locations": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** List all clothing locations */
    get: operations["getAllLocations"]
    put?: never
    /** Create a new clothing location */
    post: operations["createLocation"]
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/api/clothing/locations/batch": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /** Create multiple clothing locations in a single request */
    post: operations["createBatchLocations"]
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/api/clothing/items": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** List all clothing items */
    get: operations["getAllItems"]
    put?: never
    /** Create a new clothing item */
    post: operations["createItem"]
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/api/clothing/items/batch": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /** Create multiple clothing items in a single request */
    post: operations["createBatchItems"]
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/api/clothing/checkouts": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /** Perform a checkout */
    post: operations["checkout"]
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/api/admin/users": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get: operations["getAllUsers"]
    put?: never
    post: operations["createUser"]
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/api/admin/privacy-policy": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Get metadata of the active privacy policy document */
    get: operations["getMetadata"]
    put?: never
    /** Upload a new privacy policy document, replacing any existing one */
    post: operations["upload"]
    /** Delete the active privacy policy document */
    delete: operations["delete"]
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/api/clothing/types/{id}": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Get a protective clothing type by ID */
    get: operations["getTypeById"]
    put?: never
    post?: never
    /** Delete a protective clothing type */
    delete: operations["deleteType"]
    options?: never
    head?: never
    /** Update a protective clothing type */
    patch: operations["updateType"]
    trace?: never
  }
  "/api/clothing/locations/{id}": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Get a clothing location by ID */
    get: operations["getLocationById"]
    put?: never
    post?: never
    /** Delete a clothing location */
    delete: operations["deleteLocation"]
    options?: never
    head?: never
    /** Update a clothing location */
    patch: operations["updateLocation"]
    trace?: never
  }
  "/api/clothing/items/{id}": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Get a clothing item by ID */
    get: operations["getItemById"]
    put?: never
    post?: never
    /** Delete a clothing item */
    delete: operations["deleteItem"]
    options?: never
    head?: never
    /** Update a clothing item */
    patch: operations["updateItem"]
    trace?: never
  }
  "/api/admin/users/{id}": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get: operations["getUserById"]
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch: operations["updateUser"]
    trace?: never
  }
  "/privacy-policy": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get: operations["getPrivacyPolicy"]
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/api/public/auth/me": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get: operations["me"]
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/api/clothing/overview/summary/type": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** List clothing item counts by type and size */
    get: operations["getSummariesByType"]
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/api/clothing/overview/dashboard/location": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Get clothing availability overview for dashboard locations */
    get: operations["getDashboardLocationSummaries"]
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/api/clothing/items/search": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Search clothing items by type name, size, or barcode */
    get: operations["searchItems"]
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/api/clothing/items/by-barcode/{barcode}": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Look up a clothing item by barcode */
    get: operations["getItemByBarcode"]
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/api/admin/privacy-policy/exists": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Check whether a privacy policy document has been uploaded */
    get: operations["exists"]
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
}
export type webhooks = Record<string, never>
export interface components {
  schemas: {
    ChangePasswordRequest: {
      newPassword: string
    }
    EntityMetaData: {
      /** Format: date-time */
      createdAt: string
      createdBy: string
      /** Format: date-time */
      lastModifiedAt: string
      lastModifiedBy: string
    }
    UserAccount: {
      username: string
      firstName: string
      lastName: string
      roles: ("USER" | "ADMIN" | "KLEIDERWART")[]
      enabled: boolean
      /** Format: int64 */
      id: number
      metaData: components["schemas"]["EntityMetaData"]
    }
    InitialAdminSetupRequest: {
      username: string
      password: string
      firstName: string
      lastName: string
    }
    LoginRequest: {
      username: string
      password: string
      rememberMe: boolean
    }
    CreateOrUpdateClothingTypeRequest: {
      name: string
    }
    ClothingType: {
      name: string
      /** Format: int64 */
      id: number
      metaData: components["schemas"]["EntityMetaData"]
    }
    RelocationRequest: {
      /** Format: int64 */
      targetLocationId: number
      itemIds: number[]
    }
    ProblemDetail: {
      /** Format: uri */
      type?: string
      title?: string
      /** Format: int32 */
      status?: number
      detail?: string
      /** Format: uri */
      instance?: string
      properties?: {
        [key: string]: unknown
      }
    }
    CreateClothingLocationRequest: {
      name: string
      comment: string
      onlyVisibleForKleiderwart: boolean
      /** @enum {string} */
      type: "POOL" | "WAESCHE" | "PERSONAL" | "OTHER"
    }
    ClothingLocation: {
      name: string
      comment: string
      onlyVisibleForKleiderwart: boolean
      /** @enum {string} */
      type: "POOL" | "WAESCHE" | "PERSONAL" | "OTHER"
      /** Format: int64 */
      id: number
      metaData: components["schemas"]["EntityMetaData"]
    }
    BatchCreateClothingLocationsRequest: {
      items: components["schemas"]["CreateClothingLocationRequest"][]
    }
    CreateOrUpdateClothingItemRequest: {
      /** Format: int64 */
      typeId: number
      size: string
      barcode?: string
      /** Format: int64 */
      locationId?: number
    }
    ClothingItem: {
      /** Format: int64 */
      typeId: number
      size: string
      barcode?: string
      /** Format: int64 */
      locationId?: number
      /** Format: int64 */
      id: number
      metaData: components["schemas"]["EntityMetaData"]
    }
    BatchCreateClothingItemsRequest: {
      items: components["schemas"]["CreateOrUpdateClothingItemRequest"][]
    }
    CheckoutRequest: {
      /** Format: int64 */
      targetLocationId: number
      /** Format: int64 */
      returnLocationId?: number
      takeItemIds: number[]
      returnItemIds: number[]
    }
    CheckoutResponse: {
      batchId: string
    }
    CreateUserRequest: {
      username: string
      password: string
      firstName: string
      lastName: string
      roles: ("USER" | "ADMIN" | "KLEIDERWART")[]
    }
    PrivacyPolicyMetadata: {
      fileName: string
      contentType: string
      /** Format: int64 */
      fileSize: number
      /** Format: date-time */
      uploadedAt: string
    }
    UpdateUserRequest: {
      firstName: string
      lastName: string
      roles: ("USER" | "ADMIN" | "KLEIDERWART")[]
    }
    AuthStateResponse: {
      authenticated: boolean
      user?: components["schemas"]["UserAccount"]
    }
    ClothingTypeSummary: {
      /** Format: int64 */
      typeId: number
      typeName: string
      sizeGroupSummary: components["schemas"]["SizeGroupSummary"][]
      /** Format: int32 */
      totalCount: number
    }
    SizeGroupSummary: {
      name: string
      sizes: components["schemas"]["SizeSummary"][]
      /** Format: int32 */
      totalCount: number
    }
    SizeSummary: {
      size: string
      /** Format: int32 */
      count: number
    }
    ClothingLocationSummary: {
      /** Format: int64 */
      locationId: number
      locationName: string
      types: components["schemas"]["ClothingTypeSummary"][]
      /** Format: int32 */
      totalCount: number
    }
    ResolvedClothingItem: {
      clothingItem: components["schemas"]["ClothingItem"]
      location?: components["schemas"]["ClothingLocation"]
      clothingType: components["schemas"]["ClothingType"]
    }
    PrivacyPolicyExists: {
      exists: boolean
    }
  }
  responses: never
  parameters: never
  requestBodies: never
  headers: never
  pathItems: never
}
export type $defs = Record<string, never>
export interface operations {
  changePassword: {
    parameters: {
      query?: never
      header?: never
      path: {
        id: number
      }
      cookie?: never
    }
    requestBody: {
      content: {
        "application/json": components["schemas"]["ChangePasswordRequest"]
      }
    }
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "*/*": components["schemas"]["UserAccount"]
        }
      }
    }
  }
  initializeAdmin: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        "application/json": components["schemas"]["InitialAdminSetupRequest"]
      }
    }
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "*/*": components["schemas"]["UserAccount"]
        }
      }
    }
  }
  logout: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description No Content */
      204: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
    }
  }
  login: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        "application/json": components["schemas"]["LoginRequest"]
      }
    }
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
    }
  }
  getAllTypes: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "*/*": components["schemas"]["ClothingType"][]
        }
      }
    }
  }
  createType: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        "application/json": components["schemas"]["CreateOrUpdateClothingTypeRequest"]
      }
    }
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "*/*": components["schemas"]["ClothingType"]
        }
      }
    }
  }
  relocate: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        "application/json": components["schemas"]["RelocationRequest"]
      }
    }
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description Bad Request */
      400: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "*/*": components["schemas"]["ProblemDetail"]
        }
      }
      /** @description Forbidden — KLEIDERWART role required */
      403: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "*/*": components["schemas"]["ProblemDetail"]
        }
      }
    }
  }
  getAllLocations: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "*/*": components["schemas"]["ClothingLocation"][]
        }
      }
    }
  }
  createLocation: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        "application/json": components["schemas"]["CreateClothingLocationRequest"]
      }
    }
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "*/*": components["schemas"]["ClothingLocation"]
        }
      }
    }
  }
  createBatchLocations: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        "application/json": components["schemas"]["BatchCreateClothingLocationsRequest"]
      }
    }
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "*/*": components["schemas"]["ClothingLocation"][]
        }
      }
    }
  }
  getAllItems: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "*/*": components["schemas"]["ClothingItem"][]
        }
      }
    }
  }
  createItem: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        "application/json": components["schemas"]["CreateOrUpdateClothingItemRequest"]
      }
    }
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "*/*": components["schemas"]["ClothingItem"]
        }
      }
    }
  }
  createBatchItems: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        "application/json": components["schemas"]["BatchCreateClothingItemsRequest"]
      }
    }
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "*/*": components["schemas"]["ClothingItem"][]
        }
      }
    }
  }
  checkout: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        "application/json": components["schemas"]["CheckoutRequest"]
      }
    }
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "*/*": components["schemas"]["CheckoutResponse"]
        }
      }
    }
  }
  getAllUsers: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "*/*": components["schemas"]["UserAccount"][]
        }
      }
    }
  }
  createUser: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        "application/json": components["schemas"]["CreateUserRequest"]
      }
    }
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "*/*": components["schemas"]["UserAccount"]
        }
      }
    }
  }
  getMetadata: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "*/*": components["schemas"]["PrivacyPolicyMetadata"]
        }
      }
      /** @description No privacy policy document has been uploaded */
      404: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "*/*": components["schemas"]["ProblemDetail"]
        }
      }
    }
  }
  upload: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: {
      content: {
        "multipart/form-data": {
          /** Format: binary */
          file: string
        }
      }
    }
    responses: {
      /** @description Created */
      201: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "*/*": components["schemas"]["PrivacyPolicyMetadata"]
        }
      }
      /** @description Unsupported file type or file too large */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "*/*": components["schemas"]["ProblemDetail"]
        }
      }
    }
  }
  delete: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description No Content */
      204: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
    }
  }
  getTypeById: {
    parameters: {
      query?: never
      header?: never
      path: {
        /** @description ID of the protective clothing type */
        id: number
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "*/*": components["schemas"]["ClothingType"]
        }
      }
    }
  }
  deleteType: {
    parameters: {
      query?: never
      header?: never
      path: {
        /** @description ID of the protective clothing type */
        id: number
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description No Content */
      204: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description Not Found */
      404: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "*/*": components["schemas"]["ProblemDetail"]
        }
      }
      /** @description Conflict – type still referenced by clothing items */
      409: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "*/*": components["schemas"]["ProblemDetail"]
        }
      }
    }
  }
  updateType: {
    parameters: {
      query?: never
      header?: never
      path: {
        /** @description ID of the protective clothing type */
        id: number
      }
      cookie?: never
    }
    requestBody: {
      content: {
        "application/json": components["schemas"]["CreateOrUpdateClothingTypeRequest"]
      }
    }
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "*/*": components["schemas"]["ClothingType"]
        }
      }
    }
  }
  getLocationById: {
    parameters: {
      query?: never
      header?: never
      path: {
        /** @description ID of the clothing location */
        id: number
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "*/*": components["schemas"]["ClothingLocation"]
        }
      }
    }
  }
  deleteLocation: {
    parameters: {
      query?: never
      header?: never
      path: {
        /** @description ID of the clothing location */
        id: number
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description No Content */
      204: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
    }
  }
  updateLocation: {
    parameters: {
      query?: never
      header?: never
      path: {
        /** @description ID of the clothing location */
        id: number
      }
      cookie?: never
    }
    requestBody: {
      content: {
        "application/json": components["schemas"]["CreateClothingLocationRequest"]
      }
    }
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "*/*": components["schemas"]["ClothingLocation"]
        }
      }
    }
  }
  getItemById: {
    parameters: {
      query?: never
      header?: never
      path: {
        /** @description ID of the clothing item */
        id: number
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "*/*": components["schemas"]["ClothingItem"]
        }
      }
    }
  }
  deleteItem: {
    parameters: {
      query?: never
      header?: never
      path: {
        /** @description ID of the clothing item */
        id: number
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description No Content */
      204: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
    }
  }
  updateItem: {
    parameters: {
      query?: never
      header?: never
      path: {
        /** @description ID of the clothing item */
        id: number
      }
      cookie?: never
    }
    requestBody: {
      content: {
        "application/json": components["schemas"]["CreateOrUpdateClothingItemRequest"]
      }
    }
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "*/*": components["schemas"]["ClothingItem"]
        }
      }
    }
  }
  getUserById: {
    parameters: {
      query?: never
      header?: never
      path: {
        id: number
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "*/*": components["schemas"]["UserAccount"]
        }
      }
    }
  }
  updateUser: {
    parameters: {
      query?: never
      header?: never
      path: {
        id: number
      }
      cookie?: never
    }
    requestBody: {
      content: {
        "application/json": components["schemas"]["UpdateUserRequest"]
      }
    }
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "*/*": components["schemas"]["UserAccount"]
        }
      }
    }
  }
  getPrivacyPolicy: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "*/*": string
        }
      }
    }
  }
  me: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "*/*": components["schemas"]["AuthStateResponse"]
        }
      }
    }
  }
  getSummariesByType: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "*/*": components["schemas"]["ClothingTypeSummary"][]
        }
      }
    }
  }
  getDashboardLocationSummaries: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "*/*": components["schemas"]["ClothingLocationSummary"][]
        }
      }
    }
  }
  searchItems: {
    parameters: {
      query: {
        q: string
        limit?: number
      }
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "*/*": components["schemas"]["ResolvedClothingItem"][]
        }
      }
    }
  }
  getItemByBarcode: {
    parameters: {
      query?: never
      header?: never
      path: {
        barcode: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "*/*": components["schemas"]["ResolvedClothingItem"]
        }
      }
    }
  }
  exists: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "*/*": components["schemas"]["PrivacyPolicyExists"]
        }
      }
    }
  }
}
