/**
 * @generated by `astryx theme build` — do not edit manually.
 * Source: src/theme/appTheme.ts
 * Command: astryx theme build src/theme/appTheme.ts --out src/theme/built/open-fire-station.css
 * CLI: @astryxdesign/cli@0.6.6
 * Core: @astryxdesign/core@0.6.6
 */

// Generated by astryx theme build
export {};

declare module '@astryxdesign/core/Badge' {
  interface BadgeVariantMap {
    'gray': true;
  }
}
