/**
 * @generated by `astryx theme build` — do not edit manually.
 * Source: src/theme/appTheme.ts
 * Command: astryx theme build src/theme/appTheme.ts --out src/theme/built/open-fire-station.css
 * CLI: @astryxdesign/cli@0.6.6
 * Core: @astryxdesign/core@0.6.6
 */

/// <reference path="./open-fire-station.variants.d.ts" />
import type { DefinedTheme } from '@astryxdesign/core/theme';
import type { IconRegistry } from '@astryxdesign/core/Icon';
export declare const themeIcons: IconRegistry;
export declare const openFireStationTheme: DefinedTheme;
