service:
  app:
    image: ghcr.io/simonhauck/open-fire-station-manager:latest
    restart: unless-stopped
    environment:
      SPRING_PROFILES_ACTIVE: prod
      DB_URL: ${DB_URL}
      REMEMBER_ME_KEY: ${REMEMBER_ME_KEY}
    ports:
      - "13842:8080"