/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as NutzermanagementIndexRouteImport } from './routes/nutzermanagement/index'
import { Route as KlamottenmanagementIndexRouteImport } from './routes/klamottenmanagement/index'
import { Route as NutzermanagementNewRouteImport } from './routes/nutzermanagement/new'
import { Route as KlamottenmanagementTypesRouteImport } from './routes/klamottenmanagement/types'
import { Route as NutzermanagementUserIdEditRouteImport } from './routes/nutzermanagement/$userId/edit'
import { Route as NutzermanagementUserIdChangePasswordRouteImport } from './routes/nutzermanagement/$userId/change-password'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const NutzermanagementIndexRoute = NutzermanagementIndexRouteImport.update({
  id: '/nutzermanagement/',
  path: '/nutzermanagement/',
  getParentRoute: () => rootRouteImport,
} as any)
const KlamottenmanagementIndexRoute =
  KlamottenmanagementIndexRouteImport.update({
    id: '/klamottenmanagement/',
    path: '/klamottenmanagement/',
    getParentRoute: () => rootRouteImport,
  } as any)
const NutzermanagementNewRoute = NutzermanagementNewRouteImport.update({
  id: '/nutzermanagement/new',
  path: '/nutzermanagement/new',
  getParentRoute: () => rootRouteImport,
} as any)
const KlamottenmanagementTypesRoute =
  KlamottenmanagementTypesRouteImport.update({
    id: '/klamottenmanagement/types',
    path: '/klamottenmanagement/types',
    getParentRoute: () => rootRouteImport,
  } as any)
const NutzermanagementUserIdEditRoute =
  NutzermanagementUserIdEditRouteImport.update({
    id: '/nutzermanagement/$userId/edit',
    path: '/nutzermanagement/$userId/edit',
    getParentRoute: () => rootRouteImport,
  } as any)
const NutzermanagementUserIdChangePasswordRoute =
  NutzermanagementUserIdChangePasswordRouteImport.update({
    id: '/nutzermanagement/$userId/change-password',
    path: '/nutzermanagement/$userId/change-password',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/login': typeof LoginRoute
  '/klamottenmanagement/types': typeof KlamottenmanagementTypesRoute
  '/nutzermanagement/new': typeof NutzermanagementNewRoute
  '/klamottenmanagement/': typeof KlamottenmanagementIndexRoute
  '/nutzermanagement/': typeof NutzermanagementIndexRoute
  '/nutzermanagement/$userId/change-password': typeof NutzermanagementUserIdChangePasswordRoute
  '/nutzermanagement/$userId/edit': typeof NutzermanagementUserIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/login': typeof LoginRoute
  '/klamottenmanagement/types': typeof KlamottenmanagementTypesRoute
  '/nutzermanagement/new': typeof NutzermanagementNewRoute
  '/klamottenmanagement': typeof KlamottenmanagementIndexRoute
  '/nutzermanagement': typeof NutzermanagementIndexRoute
  '/nutzermanagement/$userId/change-password': typeof NutzermanagementUserIdChangePasswordRoute
  '/nutzermanagement/$userId/edit': typeof NutzermanagementUserIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/login': typeof LoginRoute
  '/klamottenmanagement/types': typeof KlamottenmanagementTypesRoute
  '/nutzermanagement/new': typeof NutzermanagementNewRoute
  '/klamottenmanagement/': typeof KlamottenmanagementIndexRoute
  '/nutzermanagement/': typeof NutzermanagementIndexRoute
  '/nutzermanagement/$userId/change-password': typeof NutzermanagementUserIdChangePasswordRoute
  '/nutzermanagement/$userId/edit': typeof NutzermanagementUserIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/login'
    | '/klamottenmanagement/types'
    | '/nutzermanagement/new'
    | '/klamottenmanagement/'
    | '/nutzermanagement/'
    | '/nutzermanagement/$userId/change-password'
    | '/nutzermanagement/$userId/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/login'
    | '/klamottenmanagement/types'
    | '/nutzermanagement/new'
    | '/klamottenmanagement'
    | '/nutzermanagement'
    | '/nutzermanagement/$userId/change-password'
    | '/nutzermanagement/$userId/edit'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/login'
    | '/klamottenmanagement/types'
    | '/nutzermanagement/new'
    | '/klamottenmanagement/'
    | '/nutzermanagement/'
    | '/nutzermanagement/$userId/change-password'
    | '/nutzermanagement/$userId/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  LoginRoute: typeof LoginRoute
  KlamottenmanagementTypesRoute: typeof KlamottenmanagementTypesRoute
  NutzermanagementNewRoute: typeof NutzermanagementNewRoute
  KlamottenmanagementIndexRoute: typeof KlamottenmanagementIndexRoute
  NutzermanagementIndexRoute: typeof NutzermanagementIndexRoute
  NutzermanagementUserIdChangePasswordRoute: typeof NutzermanagementUserIdChangePasswordRoute
  NutzermanagementUserIdEditRoute: typeof NutzermanagementUserIdEditRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nutzermanagement/': {
      id: '/nutzermanagement/'
      path: '/nutzermanagement'
      fullPath: '/nutzermanagement/'
      preLoaderRoute: typeof NutzermanagementIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/klamottenmanagement/': {
      id: '/klamottenmanagement/'
      path: '/klamottenmanagement'
      fullPath: '/klamottenmanagement/'
      preLoaderRoute: typeof KlamottenmanagementIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nutzermanagement/new': {
      id: '/nutzermanagement/new'
      path: '/nutzermanagement/new'
      fullPath: '/nutzermanagement/new'
      preLoaderRoute: typeof NutzermanagementNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/klamottenmanagement/types': {
      id: '/klamottenmanagement/types'
      path: '/klamottenmanagement/types'
      fullPath: '/klamottenmanagement/types'
      preLoaderRoute: typeof KlamottenmanagementTypesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nutzermanagement/$userId/edit': {
      id: '/nutzermanagement/$userId/edit'
      path: '/nutzermanagement/$userId/edit'
      fullPath: '/nutzermanagement/$userId/edit'
      preLoaderRoute: typeof NutzermanagementUserIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nutzermanagement/$userId/change-password': {
      id: '/nutzermanagement/$userId/change-password'
      path: '/nutzermanagement/$userId/change-password'
      fullPath: '/nutzermanagement/$userId/change-password'
      preLoaderRoute: typeof NutzermanagementUserIdChangePasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  LoginRoute: LoginRoute,
  KlamottenmanagementTypesRoute: KlamottenmanagementTypesRoute,
  NutzermanagementNewRoute: NutzermanagementNewRoute,
  KlamottenmanagementIndexRoute: KlamottenmanagementIndexRoute,
  NutzermanagementIndexRoute: NutzermanagementIndexRoute,
  NutzermanagementUserIdChangePasswordRoute:
    NutzermanagementUserIdChangePasswordRoute,
  NutzermanagementUserIdEditRoute: NutzermanagementUserIdEditRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
