name: CI

on:
  pull_request:
  workflow_dispatch:
  workflow_call:

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Setup build environment
        uses: ./.github/actions/setup-build-env

      - name: Run backend checks
        run: ./gradlew check

      - name: Install client dependencies
        working-directory: client
        run: npm ci

      - name: Lint client
        working-directory: client
        run: npm run lint

      - name: Check client formatting
        working-directory: client
        run: npm run format
