name: On Main Push

on:
  push:
    branches:
      - main

jobs:
  run-tests:
    permissions:
      contents: read
    uses: ./.github/workflows/ci.yml

  publish-docker-snapshot:
    needs: run-tests
    permissions:
      contents: read
      packages: write
    uses: ./.github/workflows/publish-docker-image.yml
    secrets: inherit

  deploy-develop:
    needs: publish-docker-snapshot
    permissions:
      contents: read
    uses: ./.github/workflows/deploy.yml
    with:
      environment: develop
    secrets: inherit
