name: On Release Tag

on:
  push:
    tags:
      - "v*"

jobs:
  run-tests:
    permissions:
      contents: read
    uses: ./.github/workflows/ci.yml

  publish-docker-release:
    needs: run-tests
    permissions:
      contents: read
      packages: write
    uses: ./.github/workflows/publish-docker-image.yml
    secrets: inherit

  publish-github-release:
    needs: publish-docker-release
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Create GitHub release
        uses: softprops/action-gh-release@v3
        with:
          generate_release_notes: true
          make_latest: true

  deploy-production:
    needs: publish-docker-release
    permissions:
      contents: read
    uses: ./.github/workflows/deploy.yml
    with:
      environment: production
    secrets: inherit
