name: Publish

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  ci:
    uses: ./.github/workflows/ci.yml
    secrets: inherit

  publish:
    needs: ci
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Setup build environment
        uses: ./.github/actions/setup-build-env

      - name: Install client dependencies
        working-directory: client
        run: npm ci

      - name: Build client
        working-directory: client
        run: npm run build

      - name: Publish Docker image
        shell: bash
        working-directory: server
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: ./gradlew jib
